name: Slack integration
on:
  pull_request:
    types:
      - opened
jobs:
  slack:
    runs-on: ubuntu-latest
    steps:
      - name: Escape pull request title
        id: escaping-for-slack
        # Workaround for pull request titles with double quotes 
        run: |
          import json
          import os
          with open('${{ github.event_path }}') as fh:
              event = json.load(fh)
          title = event['pull_request']['title']
          escaped = title.replace('"', '\\"').replace('&', '&amp;').replace('<', '&lt;').replace('>', '&gt;')
          with open(os.environ['GITHUB_OUTPUT'], 'a') as fh:
              print(f"PR_TITLE={escaped}", file=fh)
        shell: python3 {0}
      - name: Send custom JSON data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.24.0
        with:
          # For posting a rich message using Block Kit
          payload: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "<${{ github.event.pull_request.html_url }}|${{ steps.escaping-for-slack.outputs.PR_TITLE }}> by <${{ github.event.pull_request.user.html_url }}|${{ github.event.pull_request.user.login }}>"
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
